#!/usr/bin/env python3
"""Converts the 32x32 icons of the IndiaNavi firmware into modules/icons.js.

Usage: tools/generate_icons.py [path to IndiaNavi_Firmware/lib/icons_32]

The firmware stores every icon as 4 bit per pixel, the value is the index of the display color
(see DISPLAY_COLORS in modules/map_color.js), 7 is transparent.
"""
import glob
import os
import re
import sys

source = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    os.path.dirname(__file__), '..', '..', 'IndiaNavi_Firmware', 'lib', 'icons_32')
target = os.path.join(os.path.dirname(__file__), '..', 'modules', 'icons.js')

SIZE = 32
icons = {}
for path in sorted(glob.glob(os.path.join(source, '*.c'))):
    name = os.path.basename(path).split('.')[0]
    data = [int(value, 16) for value in re.findall(r'0x([0-9a-fA-F]{2})', open(path).read())]
    assert len(data) == SIZE * SIZE // 2, f'{name}: {len(data)} bytes'
    pixels = ''.join(f'{byte >> 4:x}{byte & 15:x}' for byte in data)
    assert max(pixels) <= '7', f'{name}: unknown color'
    icons[name] = [pixels[row * SIZE:(row + 1) * SIZE] for row in range(SIZE)]

with open(target, 'w') as out:
    out.write('// Generated by tools/generate_icons.py from the icons of the IndiaNavi firmware. Do not edit.\n')
    out.write('// Every icon is 32 rows of 32 characters, the character is the index of the display color,\n')
    out.write('// 7 is transparent.\n\n')
    out.write(f'export const ICON_SIZE = {SIZE};\n\n')
    out.write('export const ICONS = {\n')
    for name, rows in icons.items():
        out.write(f'  {name}: [\n')
        for row in rows:
            out.write(f"    '{row}',\n")
        out.write('  ],\n')
    out.write('};\n')
print(f'{len(icons)} icons: {", ".join(icons)}')
